<!-- ====================== DASHBOARD COLETIVO ====================== -->
<div class="page-header d-flex flex-wrap justify-content-center justify-content-md-between align-items-center">
    <div>
        <h4 class="mb-0">Dashboard Coletivo</h4>
    </div>
    <form id="form_periodo_grupo" class="form-inline mr-2 mb-0 mb-md-2 mt-3 mt-md-0">
        <div class="form-group">
            <input style="min-width:240px; background:#fff" class="form-control text-center" type="text" id="periodo_grupo" readonly>
            <input type='hidden' id="inicio_grupo" />
            <input type='hidden' id="fim_grupo" />
        </div>
    </form>
    <div class="d-flex flex-wrap mt-2 mt-md-0">
        <div class="mr-2 mb-4 mb-md-2">
            <select id="filtroGrupoColetivo" class="form-control form-control-sm">
                <?php foreach ($this->grupos as $value): ?>
                    <option <?= ($this->id_grupo == $value['id_grupo']) ? "selected" : "" ?> value="<?= $value['id_grupo'] ?>"><?= $value['nome'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>

<div id="content-terciario"></div>

<script type="text/javascript">
    $(document).ready(function() {

        var id_grupo = <?= $this->id_grupo ?>;

        function recarregarTela() {
            carregarTela('../../dashboard/grupodetalhe?inicio=' + inicio + '&fim=' + fim + '&id_grupo=' + id_grupo, '#content-terciario');
        }

        $('#filtroGrupoColetivo').select2({
                width: '300px',
                language: "pt-BR",
                theme: 'bootstrap4'
            }).on('change', function() {
                id_grupo = $(this).val();
                recarregarTela();
            })
            .trigger('change');

        $('#inicio_grupo').val(inicio);
        $('#fim_grupo').val(fim);

        let periodo = $('#periodo_grupo').daterangepicker({
            startDate: new Date(inicio + ' 00:00:00'),
            endDate: new Date(fim + ' 23:59:59'),
            ranges: {
                'Hoje': [moment(), moment()],
                'Ontem': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Últimos 7 dias': [moment().subtract(6, 'days'), moment()],
                'Semana Atual': [moment().clone().startOf('isoWeek'), moment().clone().endOf('isoWeek')],
                'Semana Passada': [moment().clone().subtract(1, 'weeks').startOf('isoWeek'), moment().clone().subtract(1, 'weeks').endOf('isoWeek')],
                'Últimos 30 dias': [moment().subtract(29, 'days'), moment()],
                'Mês Atual': [moment().startOf('month'), moment().endOf('month')],
                'Mês Passado': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            "locale": {
                format: 'DD/MM/YYYY',
                "separator": " até ",
                "applyLabel": "Aplicar",
                "cancelLabel": "Cancelar",
                "fromLabel": "De",
                "toLabel": "Até",
                "customRangeLabel": "Selecionar Data",
                "daysOfWeek": [
                    "Dom",
                    "Seg",
                    "Ter",
                    "Qua",
                    "Qui",
                    "Sex",
                    "Sáb"
                ],
                "monthNames": [
                    "Janeiro",
                    "Fevereiro",
                    "Março",
                    "Abril",
                    "Maio",
                    "Junho",
                    "Julho",
                    "Agosto",
                    "Setembro",
                    "Outubro",
                    "Novembro",
                    "Dezembro"
                ],
                "firstDay": 0
            }
        }, function(start, end) {
            $('#inicio_grupo').val(start.format('YYYY-MM-DD'));
            $('#fim_grupo').val(end.format('YYYY-MM-DD'));
            let form = periodo.closest('form');
            form.trigger('submit');
        });

        $("#form_periodo_grupo").submit(function(e) {
            e.preventDefault();
            inicio = $("#inicio_grupo").val();
            fim = $("#fim_grupo").val();
            recarregarTela();
        });

    });
</script>