 <div class="container-fluid py-1">
     <!-- Abas de Navegação -->
     <ul class="nav nav-tabs mb-2" id="tabDashboards" role="tablist">
         <li class="nav-item">
             <a class="nav-link active" data-dashboard="grupo" data-toggle="tab"
                 href="#pane-coletivo" role="tab" aria-selected="true">
                 <i class="fas fa-users mr-1"></i> Grupo
             </a>
         </li>
         <li class="nav-item">
             <a class="nav-link" data-dashboard="usuario" data-toggle="tab"
                 href="#pane-individual" role="tab" aria-selected="false">
                 <i class="fas fa-user mr-1"></i> Colaborador
             </a>
         </li>
     </ul>

     <div class="tab-pane" role="tabpanel" aria-labelledby="tab-coletivo" id="content-secundario"></div>

 </div>

 <script type="text/javascript">   

     $(document).ready(function() {

         $('#tabDashboards .nav-link').on('click', function() {
             let dashboard = $(this).data('dashboard');
             carregarTela('../../dashboard/' + dashboard, '#content-secundario');
         });

         carregarTela('../../dashboard/grupo', '#content-secundario');

     });
 </script>