<!-- ====================== DASHBOARD INDIVIDUAL ====================== -->

<div class="page-header d-flex flex-wrap justify-content-between align-items-center">
  <div>
    <h4 class="mb-0">Dashboard Colaborador</h4>
    <small>Notas de um colaborador.</small>
  </div>
  <div class="d-flex flex-wrap mt-2 mt-md-0">
    <!-- Filtros -->
    <div class="mr-2 mb-2">
      <label class="small mb-1 font-weight-bold mb-0">Colaborador</label>
      <select id="filtroColaboradorIndividual" class="form-control form-control-sm">
        <?php foreach ($this->usuarios as $value): ?>
          <option <?= ($this->id_usuario == $value['id_usuario']) ? "selected" : "" ?> value="<?= $value['id_usuario'] ?>"><?= $value['nome'] ?></option>
        <?php endforeach; ?>
      </select>
    </div>
  </div>
</div>

<div id="content-terciario"></div>

<script type="text/javascript">
  $(document).ready(function() {

    $('#filtroColaboradorIndividual').select2({
        width: '100%',
        language: "pt-BR",
        theme: 'bootstrap4'
      }).on('change', function() {
        carregarTela('../../dashboard/usuariodetalhe', '#content-terciario');
      })
      .trigger('change');

  });
</script>