<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Base</h1>
	<div class="btn-toolbar mb-2 mb-md-0">
		<div class="btn-group mr-2">
			<button type="button" onclick="carregarTela('../../base')" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>
		</div>
	</div>
</div>
<form id="formulario_base">
	<input name="id_base" type="hidden" value="<?= $this->registro ? $this->registro['id_base'] : '' ?>" id="id_base">

	<div class="row">
		<div class="form-group col-md-12">
			<span><label for="nome">Nome: </label></span>
			<input required class="form-control" minlength="2" maxlength="255" name="nome" type="text" value="<?= $this->registro ? $this->registro['nome'] : '' ?>" id="nome">
		</div>
	</div>

	<div class="row">
		<div class="form-group col-12 text-right">
			<button class="btn btn-success salvar"><span class="glyphicon glyphicon-floppy-disk"></span><i class="fa fa-floppy-o"></i> Salvar</button>
		</div>
	</div>
</form>

<script type="text/javascript">
	$(document).ready(function() {
		$('#nome').focus();
	});

	$("#formulario_base").submit(function(e) {

		var erro = "";

		if (erro != "") {
			swal({
				title: "Atenção!",
				text: erro,
				type: "error"
			});
			return false;
		}
		$('.salvar').hide();
		$.ajax({
			type: "POST",
			url: "../../base/salvar",
			data: $("#formulario_base").serialize(),
			success: function(data) {

				// falha ao salvar
				if (data.trim().length > 0) {
					$('.salvar').show();
					swal({
						title: "Atenção!",
						text: data,
						type: "error"
					});
					// sucesso ao salvar
				} else {
					carregarTela('../../base');
				}
			}
		});

		e.preventDefault();
	});
</script>