<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Grupo</h1>
	<div class="btn-toolbar mb-2 mb-md-0">
		<div class="btn-group mr-2">
			<button type="button" onclick="carregarTela('../../grupo')" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>
		</div>
	</div>
</div>
<form id="formulario_grupo">
	<input name="id_grupo" type="hidden" value="<?= $this->registro ? $this->registro['id_grupo'] : '' ?>" id="id_grupo">

	<div class="row">
		<div class="form-group col-md-12">
			<span><label for="nome">Nome: </label></span>
			<input required class="form-control" minlength="2" maxlength="255" name="nome" type="text" value="<?= $this->registro ? $this->registro['nome'] : '' ?>" id="nome">
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-6">
			<span><label for="id_usuario">* Responsável: </label></span>
			<select required class="form-control" name="id_usuario" id="id_usuario">
				<? if (count($this->responsaveis)) foreach ($this->responsaveis as $key => $value) : ?>
					<option value="<?= $value['id_usuario'] ?>"><?= $value['nome'] ?></option>
				<? endforeach; ?>
			</select>
		</div>
		<div class="form-group col-md-6">
			<span><label for="id_formulario">* Formulario: </label></span>
			<select required class="form-control" name="id_formulario" id="id_formulario">
				<? if (count($this->formularios)) foreach ($this->formularios as $key => $value) : ?>
					<option value="<?= $value['id_formulario'] ?>"><?= $value['nome'] ?></option>
				<? endforeach; ?>
			</select>
		</div>
	</div>

	<div class="row mb-4">
		<div class="col-md-6">
			<div class="card border-0">
				<div class="card-header bg-cinza">DISPONÍVEIS</div>
				<ul style="min-height:100px;max-height:500px;overflow:auto" class="list-group card-body p-0" id="disponiveis">
					<? if (count($this->usuarios) > 0)
						foreach ($this->usuarios as $key => $value) :
							if (isset($this->membros[$value['id_usuario']])) continue; ?>
						<li class="list-group-item border" style="cursor:move">
							<i class="fa fa-arrows pull-right"></i>
							<strong><?= $value['nome'] ?></strong>
							<input type="hidden" name="usuario_<?= $value['id_usuario'] ?>" value="" />
						</li>
					<? endforeach; ?>
				</ul>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card border-0">
				<div class="card-header bg-danger text-white">SELECIONADOS</div>
				<ul style="min-height:100px;max-height:500px;overflow:auto" class="list-group card-body p-0" id="selecionados">
					<? if ($this->registro && count($this->membros))
						foreach ($this->membros as $key => $value) : ?>
						<li class="list-group-item border">
							<i class="fa fa-arrows pull-right" style="cursor:move"></i>
							<strong><?= $value['nome'] ?></strong>
							<input type="hidden" name="usuario_<?= $value['id_usuario'] ?>" value="1" />
						</li>
					<? endforeach; ?>
				</ul>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="form-group col-12 text-right">
			<button class="btn btn-success salvar"><span class="glyphicon glyphicon-floppy-disk"></span><i class="fa fa-floppy-o"></i> Salvar</button>
		</div>
	</div>
</form>

<script type="text/javascript">
	$(document).ready(function() {
		$('#nome').focus();

		$('#disponiveis').sortable({
			animation: 100,
			group: 'list-1',
			sort: true,
			//filter: '.sortable-disabled',
			chosenClass: 'active',
			onAdd: function(evt) {
				$(evt.item).find('input').val('');
			}
		});

		$('#selecionados').sortable({
			group: 'list-1',
			onAdd: function(evt) {
				$(evt.item).find('input').val('1');
			}
		});

		$('#id_formulario').select2({
			width: '100%',
			language: "pt-BR",
			theme: 'bootstrap4'
		}).val(<?= ($this->registro && $this->registro['id_formulario']) ? $this->registro['id_formulario'] : '-1' ?>).trigger('change');

		$('#id_usuario').select2({
			width: '100%',
			language: "pt-BR",
			theme: 'bootstrap4'
		}).val(<?= ($this->registro && $this->registro['id_usuario']) ? $this->registro['id_usuario'] : '-1' ?>).trigger('change');

		$("#formulario_grupo").submit(function(e) {
			var erro = "";
			if (erro != "") {
				swal({
					title: "Atenção!",
					text: erro,
					type: "error"
				});
				return false;
			}
			$('.salvar').hide();
			$.ajax({
				type: "POST",
				url: "../../grupo/salvar",
				data: $("#formulario_grupo").serialize(),
				success: function(data) {

					// falha ao salvar
					if (data.trim().length > 0) {
						$('.salvar').show();
						swal({
							title: "Atenção!",
							text: data,
							type: "error"
						});
						// sucesso ao salvar
					} else {
						carregarTela('../../grupo');
					}
				}
			});

			e.preventDefault();
		});
	});
</script>