<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Grupo</h1>
	<div class="btn-toolbar mb-2 mb-md-0">
		<div class="btn-group mr-2">
			<button type="button" onclick="carregarTela('../../grupo')" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>
		</div>
	</div>
</div>
<form id="formulario_grupo">
	<input name="id_grupo" type="hidden" value="<?= $this->registro ? $this->registro['id_grupo'] : '' ?>" id="id_grupo">

	<div class="row">
		<div class="form-group col-md-12">
			<span><label for="nome">Nome: </label></span>
			<input required class="form-control" minlength="2" maxlength="255" name="nome" type="text" value="<?= $this->registro ? $this->registro['nome'] : '' ?>" id="nome">
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-6">
			<span><label for="id_usuario">* Responsável: </label></span>
			<select required class="form-control" name="id_usuario" id="id_usuario">
				<? if (count($this->responsaveis)) foreach ($this->responsaveis as $key => $value) : ?>
					<option value="<?= $value['id_usuario'] ?>"><?= $value['nome'] ?></option>
				<? endforeach; ?>
			</select>
		</div>
		<div class="form-group col-md-6">
			<span><label for="id_formulario">* Formulario: </label></span>
			<select required class="form-control" name="id_formulario" id="id_formulario">
				<? if (count($this->formularios)) foreach ($this->formularios as $key => $value) : ?>
					<option value="<?= $value['id_formulario'] ?>"><?= $value['nome'] ?></option>
				<? endforeach; ?>
			</select>
		</div>
	</div>

	<div class="row">
		<div class="form-group col-12 text-right">
			<button class="btn btn-success salvar"><span class="glyphicon glyphicon-floppy-disk"></span><i class="fa fa-floppy-o"></i> Salvar</button>
		</div>
	</div>
</form>

<script type="text/javascript">
	$(document).ready(function() {
		$('#nome').focus();

		$('#id_formulario').select2({
			width: '100%',
			language: "pt-BR",
			theme: 'bootstrap4'
		}).val(<?= ($this->registro && $this->registro['id_formulario']) ? $this->registro['id_formulario'] : '-1' ?>).trigger('change');

		$('#id_usuario').select2({
			width: '100%',
			language: "pt-BR",
			theme: 'bootstrap4'
		}).val(<?= ($this->registro && $this->registro['id_usuario']) ? $this->registro['id_usuario'] : '-1' ?>).trigger('change');

		$("#formulario_grupo").submit(function(e) {
			var erro = "";
			if (erro != "") {
				swal({
					title: "Atenção!",
					text: erro,
					type: "error"
				});
				return false;
			}
			$('.salvar').hide();
			$.ajax({
				type: "POST",
				url: "../../grupo/salvar",
				data: $("#formulario_grupo").serialize(),
				success: function(data) {

					// falha ao salvar
					if (data.trim().length > 0) {
						$('.salvar').show();
						swal({
							title: "Atenção!",
							text: data,
							type: "error"
						});
						// sucesso ao salvar
					} else {
						carregarTela('../../grupo');
					}
				}
			});

			e.preventDefault();
		});
	});
</script>